# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_menu(object):
    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(menu.sizePolicy().hasHeightForWidth())
        menu.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/emoji_x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        menu.setWindowIcon(icon)
        self.titleLabel = QtWidgets.QLabel(menu)
        self.titleLabel.setGeometry(QtCore.QRect(10, 10, 781, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.titleLabel.setFont(font)
        self.titleLabel.setAcceptDrops(True)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.playButton = QtWidgets.QPushButton(menu)
        self.playButton.setGeometry(QtCore.QRect(610, 550, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.playButton.setFont(font)
        self.playButton.setObjectName("playButton")
        self.titleLabel2 = QtWidgets.QLabel(menu)
        self.titleLabel2.setGeometry(QtCore.QRect(10, 50, 781, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.titleLabel2.setFont(font)
        self.titleLabel2.setAcceptDrops(True)
        self.titleLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel2.setObjectName("titleLabel2")
        self.playerLabel = QtWidgets.QLabel(menu)
        self.playerLabel.setGeometry(QtCore.QRect(20, 80, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.playerLabel.setFont(font)
        self.playerLabel.setAcceptDrops(True)
        self.playerLabel.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.playerLabel.setObjectName("playerLabel")
        self.playAsCross = QtWidgets.QPushButton(menu)
        self.playAsCross.setGeometry(QtCore.QRect(280, 80, 111, 110))
        self.playAsCross.setText("")
        self.playAsCross.setIcon(icon)
        self.playAsCross.setIconSize(QtCore.QSize(100, 100))
        self.playAsCross.setObjectName("playAsCross")
        self.crossLabel = QtWidgets.QLabel(menu)
        self.crossLabel.setGeometry(QtCore.QRect(280, 190, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.crossLabel.setFont(font)
        self.crossLabel.setAcceptDrops(True)
        self.crossLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.crossLabel.setObjectName("crossLabel")
        self.playAsNought = QtWidgets.QPushButton(menu)
        self.playAsNought.setGeometry(QtCore.QRect(420, 80, 111, 110))
        self.playAsNought.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../assets/emoji_o.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playAsNought.setIcon(icon1)
        self.playAsNought.setIconSize(QtCore.QSize(100, 100))
        self.playAsNought.setObjectName("playAsNought")
        self.noughtLabel = QtWidgets.QLabel(menu)
        self.noughtLabel.setGeometry(QtCore.QRect(420, 190, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.noughtLabel.setFont(font)
        self.noughtLabel.setAcceptDrops(True)
        self.noughtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.noughtLabel.setObjectName("noughtLabel")
        self.line = QtWidgets.QFrame(menu)
        self.line.setGeometry(QtCore.QRect(20, 215, 761, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.algorithmLabel = QtWidgets.QLabel(menu)
        self.algorithmLabel.setGeometry(QtCore.QRect(20, 240, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.algorithmLabel.setFont(font)
        self.algorithmLabel.setAcceptDrops(True)
        self.algorithmLabel.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.algorithmLabel.setObjectName("algorithmLabel")
        self.algorithmDropdown = QtWidgets.QComboBox(menu)
        self.algorithmDropdown.setGeometry(QtCore.QRect(390, 240, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.algorithmDropdown.setFont(font)
        self.algorithmDropdown.setObjectName("algorithmDropdown")
        self.algorithmDropdown.addItem("")
        self.algorithmDescription = QtWidgets.QLabel(menu)
        self.algorithmDescription.setGeometry(QtCore.QRect(20, 290, 591, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.algorithmDescription.setFont(font)
        self.algorithmDescription.setAcceptDrops(True)
        self.algorithmDescription.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.algorithmDescription.setWordWrap(True)
        self.algorithmDescription.setObjectName("algorithmDescription")
        self.line_2 = QtWidgets.QFrame(menu)
        self.line_2.setGeometry(QtCore.QRect(20, 360, 761, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.sizeLabel = QtWidgets.QLabel(menu)
        self.sizeLabel.setGeometry(QtCore.QRect(20, 380, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sizeLabel.setFont(font)
        self.sizeLabel.setAcceptDrops(True)
        self.sizeLabel.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.sizeLabel.setObjectName("sizeLabel")
        self.play3x3 = QtWidgets.QPushButton(menu)
        self.play3x3.setGeometry(QtCore.QRect(20, 420, 111, 110))
        self.play3x3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../assets/3x3board.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play3x3.setIcon(icon2)
        self.play3x3.setIconSize(QtCore.QSize(100, 100))
        self.play3x3.setObjectName("play3x3")
        self.size3x3Label = QtWidgets.QLabel(menu)
        self.size3x3Label.setGeometry(QtCore.QRect(20, 530, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.size3x3Label.setFont(font)
        self.size3x3Label.setAcceptDrops(True)
        self.size3x3Label.setAlignment(QtCore.Qt.AlignCenter)
        self.size3x3Label.setObjectName("size3x3Label")
        self.play5x5 = QtWidgets.QPushButton(menu)
        self.play5x5.setGeometry(QtCore.QRect(160, 420, 111, 110))
        self.play5x5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../assets/5x5board.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play5x5.setIcon(icon3)
        self.play5x5.setIconSize(QtCore.QSize(100, 100))
        self.play5x5.setObjectName("play5x5")
        self.size5x5Label = QtWidgets.QLabel(menu)
        self.size5x5Label.setGeometry(QtCore.QRect(160, 530, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.size5x5Label.setFont(font)
        self.size5x5Label.setAcceptDrops(True)
        self.size5x5Label.setAlignment(QtCore.Qt.AlignCenter)
        self.size5x5Label.setObjectName("size5x5Label")
        self.play7x7 = QtWidgets.QPushButton(menu)
        self.play7x7.setGeometry(QtCore.QRect(300, 420, 111, 110))
        self.play7x7.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../assets/7x7board.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play7x7.setIcon(icon4)
        self.play7x7.setIconSize(QtCore.QSize(100, 100))
        self.play7x7.setObjectName("play7x7")
        self.size7x7Label = QtWidgets.QLabel(menu)
        self.size7x7Label.setGeometry(QtCore.QRect(300, 530, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.size7x7Label.setFont(font)
        self.size7x7Label.setAcceptDrops(True)
        self.size7x7Label.setAlignment(QtCore.Qt.AlignCenter)
        self.size7x7Label.setObjectName("size7x7Label")
        self.boardSizeDescription = QtWidgets.QLabel(menu)
        self.boardSizeDescription.setGeometry(QtCore.QRect(20, 560, 591, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.boardSizeDescription.setFont(font)
        self.boardSizeDescription.setAcceptDrops(True)
        self.boardSizeDescription.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.boardSizeDescription.setWordWrap(True)
        self.boardSizeDescription.setObjectName("boardSizeDescription")

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)

    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("menu", "Noughts and Crosses Menu"))
        self.titleLabel.setText(_translate("menu", "Play Noughts and Crosses"))
        self.playButton.setText(_translate("menu", "Play Game"))
        self.titleLabel2.setText(_translate("menu", "By Joshua Hawking"))
        self.playerLabel.setText(_translate("menu", "Who would you like to play as?"))
        self.crossLabel.setText(_translate("menu", "Cross"))
        self.noughtLabel.setText(_translate("menu", "Nought"))
        self.algorithmLabel.setText(_translate("menu", "What algorithm would you like to play against?"))
        self.algorithmDropdown.setItemText(0, _translate("menu", "Test"))
        self.algorithmDescription.setText(_translate("menu",
                                                     "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut\n"
                                                     "                    labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris\n"
                                                     "                    nisi ut aliquip ex ea commodo consequat.\n"
                                                     "                "))
        self.sizeLabel.setText(_translate("menu", "What board size would you like to play?"))
        self.size3x3Label.setText(_translate("menu", "3x3"))
        self.size5x5Label.setText(_translate("menu", "5x5"))
        self.size7x7Label.setText(_translate("menu", "7x7"))
        self.boardSizeDescription.setText(_translate("menu", "3x3: Connect 3 symbols in a row to win."))

